//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Data/UIInputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIInputSystem : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIInputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIInputSystem"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""36a1ef13-1bab-45e4-9482-0df76e753c24"",
            ""actions"": [
                {
                    ""name"": ""Space"",
                    ""type"": ""Button"",
                    ""id"": ""98147e1b-b3b8-448a-bb29-42825525240b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberOne"",
                    ""type"": ""Button"",
                    ""id"": ""c59f19f9-5f58-45bf-9698-612f26d00681"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skey"",
                    ""type"": ""Button"",
                    ""id"": ""a83fa37e-ffa4-40c6-9b2b-5384f6fa032c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ckey"",
                    ""type"": ""Button"",
                    ""id"": ""6e2d99dd-25ae-4f8f-8d94-0b564a598955"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveUI"",
                    ""type"": ""Value"",
                    ""id"": ""cba10c3b-fa70-4c30-b3e1-bf72597942c8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c7c87232-2cd4-4788-9622-b9c3a0157207"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf22dcd2-a338-4e1d-9045-e1e23a9200d4"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""554cc48d-1ca5-45d9-ae47-340e1c5b4d58"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca19d557-9314-4be9-a421-1cd5a1b17284"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ckey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c9a9a453-5a39-4b39-a822-2a4964f8a3bb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUI"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ac4cf1da-cb9f-4fa5-963f-141d83e7123a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3f91c775-ffba-4181-87ac-98ab490cf087"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b288ec52-be2b-49d8-917f-433835331531"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4d31a6ae-d0df-4a3e-8b73-e65afb0c31e1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Sleep"",
            ""id"": ""70b5109f-8f77-4c8a-822e-bed547c03a09"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Space = m_UI.FindAction("Space", throwIfNotFound: true);
        m_UI_NumberOne = m_UI.FindAction("NumberOne", throwIfNotFound: true);
        m_UI_Skey = m_UI.FindAction("Skey", throwIfNotFound: true);
        m_UI_Ckey = m_UI.FindAction("Ckey", throwIfNotFound: true);
        m_UI_MoveUI = m_UI.FindAction("MoveUI", throwIfNotFound: true);
        // Sleep
        m_Sleep = asset.FindActionMap("Sleep", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Space;
    private readonly InputAction m_UI_NumberOne;
    private readonly InputAction m_UI_Skey;
    private readonly InputAction m_UI_Ckey;
    private readonly InputAction m_UI_MoveUI;
    public struct UIActions
    {
        private @UIInputSystem m_Wrapper;
        public UIActions(@UIInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @Space => m_Wrapper.m_UI_Space;
        public InputAction @NumberOne => m_Wrapper.m_UI_NumberOne;
        public InputAction @Skey => m_Wrapper.m_UI_Skey;
        public InputAction @Ckey => m_Wrapper.m_UI_Ckey;
        public InputAction @MoveUI => m_Wrapper.m_UI_MoveUI;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Space.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSpace;
                @Space.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSpace;
                @Space.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSpace;
                @NumberOne.started -= m_Wrapper.m_UIActionsCallbackInterface.OnNumberOne;
                @NumberOne.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnNumberOne;
                @NumberOne.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnNumberOne;
                @Skey.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSkey;
                @Skey.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSkey;
                @Skey.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSkey;
                @Ckey.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCkey;
                @Ckey.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCkey;
                @Ckey.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCkey;
                @MoveUI.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMoveUI;
                @MoveUI.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMoveUI;
                @MoveUI.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMoveUI;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Space.started += instance.OnSpace;
                @Space.performed += instance.OnSpace;
                @Space.canceled += instance.OnSpace;
                @NumberOne.started += instance.OnNumberOne;
                @NumberOne.performed += instance.OnNumberOne;
                @NumberOne.canceled += instance.OnNumberOne;
                @Skey.started += instance.OnSkey;
                @Skey.performed += instance.OnSkey;
                @Skey.canceled += instance.OnSkey;
                @Ckey.started += instance.OnCkey;
                @Ckey.performed += instance.OnCkey;
                @Ckey.canceled += instance.OnCkey;
                @MoveUI.started += instance.OnMoveUI;
                @MoveUI.performed += instance.OnMoveUI;
                @MoveUI.canceled += instance.OnMoveUI;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // Sleep
    private readonly InputActionMap m_Sleep;
    private ISleepActions m_SleepActionsCallbackInterface;
    public struct SleepActions
    {
        private @UIInputSystem m_Wrapper;
        public SleepActions(@UIInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_Sleep; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SleepActions set) { return set.Get(); }
        public void SetCallbacks(ISleepActions instance)
        {
            if (m_Wrapper.m_SleepActionsCallbackInterface != null)
            {
            }
            m_Wrapper.m_SleepActionsCallbackInterface = instance;
            if (instance != null)
            {
            }
        }
    }
    public SleepActions @Sleep => new SleepActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    public interface IUIActions
    {
        void OnSpace(InputAction.CallbackContext context);
        void OnNumberOne(InputAction.CallbackContext context);
        void OnSkey(InputAction.CallbackContext context);
        void OnCkey(InputAction.CallbackContext context);
        void OnMoveUI(InputAction.CallbackContext context);
    }
    public interface ISleepActions
    {
    }
}
